export const tags: string[] = [
  "Activity",
  "Food and Drink",
  "Experience",
  "Restaurant",
  "Fast Food",
  "Activity Operator",
  "Tour",
  "Cafe",
  "Food Shops",
  "Shopping",
  "Walking",
  "Fishing",
  "Angling",
  "Nature and Wildlife",
  "Golf",
  "Attraction",
  "Historic Houses and Castle",
  "Church Abbey",
  "Monastery",
  "Churches",
  "Abbeys and Monastery",
  "Ruins",
  "Shopping Centres and Department Store",
  "Transport",
  "Coach",
  "Road",
  "Tracing",
  "Learning",
  "Cycling",
  "Bike Rental",
  "Zoos and Aquarium",
  "Museums and Attraction",
  "Tracing Your Ancestors",
  "Horse Riding",
  "Craft",
  "Artisan",
  "Climbing",
  "Kayaking",
  "Kitesurfing",
  "Windsurfing",
  "Sailing",
  "Surfing",
  "Adventure Park",
  "Boat",
  "Pampering",
  "Health Farm",
  "Spa and Wellness",
  "Specialised Retreat",
  "Spa",
  "Movies",
  "Cinema",
  "Venue",
  "Swimming",
  "Swimming Pools and Water Park",
  "Zip Lining",
  "Fitness and Leisure",
  "Swimming Pool",
  "Driving",
  "General",
  "Art",
  "Gallery",
  "Music",
  "Day Tour",
  "Agriculture",
  "Public Sculpture",
  "Seafood",
  "Falconry",
  "Natural",
  "Landscape",
  "Food Trails and Tour"
];
